In [11]:
import pandas as pd
import numpy as np
data = pd.read_excel("E:/MCA Project/100copy.xlsx" )

In [13]:
x_test=data[['Start_Lat', 'Start_Lng','start_year', 'start_month', 'start_day',
       'start_hour', 'start_minute', 'end_year', 'end_month', 'end_day',
       'end_hour', 'end_minute', 'weather_year', 'weather_month',
       'weather_day', 'weather_hour', 'weather_minute']]


In [17]:
x_test.values[0]

array([ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01])

In [63]:

import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/temperature_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01]]

temp=lr.predict(X)
temp

array([35.6738])

In [55]:
import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/pressure_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442]]

pressure=lr.predict(X)
pressure

array([29.6575])

In [56]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/humidity_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575]]

humidity=lr.predict(X)
humidity

array([94.742])

In [57]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/visibility_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742]]

visibility=lr.predict(X)
visibility

array([8.312])

In [58]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/wind_direction_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742,8.312]]

winddir=lr.predict(X)
winddir

array([6.466])

In [59]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/windchill_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742,8.312,6.466]]

windchill=lr.predict(X)
windchill

array([10.1676])

In [60]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/precipitation_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742,8.312,6.466,10.1676]]

precipitation=lr.predict(X)
precipitation

array([0.00046])

In [61]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/windspeed_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742,8.312,6.466,10.1676,0.00046]]

windspeed=lr.predict(X)
windspeed

array([4.0652])

In [62]:
 import pickle
from sklearn.externals import joblib 
lr=joblib.load('models/weathercondition_model.pkl')
X=[[ 3.9865147e+01, -8.4058723e+01,  2.0160000e+03,  2.0000000e+00,
        8.0000000e+00,  5.0000000e+00,  4.6000000e+01,  2.0160000e+03,
        2.0000000e+00,  8.0000000e+00,  1.1000000e+01,  0.0000000e+00,
        2.0160000e+03,  2.0000000e+00,  8.0000000e+00,  5.0000000e+00,
        5.8000000e+01,35.6442,29.6575,94.742,8.312,6.466,10.1676,0.00046,4.0652]]

weathercondition=lr.predict(X)
weathercondition

array([4.04])

In [68]:
data.columns

Index(['Unnamed: 0', 'TMC', 'Severity', 'Start_Lat', 'Start_Lng',
       'Distance(mi)', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Timezone', 'Airport_Code', 'Temperature(F)',
       'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Weather_Condition', 'Amenity', 'Bump', 'Crossing', 'Give_Way',
       'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop',
       'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Sunrise_Sunset',
       'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight\n',
       'start_year', 'start_month', 'start_day', 'start_hour', 'start_minute',
       'end_year', 'end_month', 'end_day', 'end_hour', 'end_minute',
       'weather_year', 'weather_month', 'weather_day', 'weather_hour',
       'weather_minute'],
      dtype='object')